version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true


formats:
  - pdf
  - epub
  - html

python:
  install:
    - method: pip
      path: .