version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false


formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt